项目_Django/myblog/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^index/$', views.index),  # 正则，^为匹配起始位置,$结尾
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article_page, name='article_page'),
    url(r'^edit/(?P<article_id>[0-9]+)/$', views.edit_page,name='edit_page'),
    url(r'^edit/action/$',views.edit_action,name='edit_action')
]

项目_Django/myblog/blog2/urls.py
from django.conf.urls import url
from blog2 import views

urlpatterns = [
    url(r'^index/$', views.index), #正则，^为匹配起始位置,$结尾
]

项目_Django/myblog/myblog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

# from blog import views as bv
# import blog.views as bv

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls',namespace='blog')), #正则，^为匹配起始位置
    url(r'^blog2/', include('blog2.urls')),
]

项目_Django/myblog/blog/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    title = models.CharField(max_length=32,default='Title')
    content = models.TextField(null=True)

    def __str__(self):
        return self.title

项目_Django/myblog/blog2/models.py
from django.db import models

# Create your models here.

项目_Django/myblog/blog/views.py
from django.shortcuts import render
from django.http import HttpResponse
from . import models


# Create your views here.

# admin
# wzl12345

def index(request):
    # return HttpResponse('Hello,World!')

    #测试
    # article = models.Article.objects.get(pk=2)
    articles = models.Article.objects.all()
    return render(request,'blog/index.html',{'articles':articles})# 'articles'是index.html中的字段

def article_page(request,article_id):
    article = models.Article.objects.get(pk=article_id)
    return render(request,'blog/article_page.html',{'article':article})

def edit_page(request,article_id):
    if str(article_id) == '0': # 不转换str，会报错 Article matching query does not exist
        return render(request,'blog/edit_page.html')
    article = models.Article.objects.get(pk=article_id)
    return render(request, 'blog/edit_page.html', {'article': article})

def edit_action(request):
    title = request.POST.get('title','TITLE')
    content = request.POST.get('content','CONTENT')
    article_id = request.POST.get('article_id','0')

    if article_id == '0':
        models.Article.objects.create(title=title,content=content)
        articles = models.Article.objects.all()
        return render(request, 'blog/index.html', {'articles': articles})# 返回主页

    article = models.Article.objects.get(pk=article_id)
    article.title = title
    article.content = content
    article.save()
    return render(request,'blog/article_page.html',{'article':article})

项目_Django/myblog/blog2/views.py
from django.shortcuts import render
from django.http import HttpResponse


# Create your views here.

def index(request):
    # return HttpResponse('Hello,World!')
    return render(request,'blog2/index.html',{'blog':'This is a Blog2!'})

项目_Django/myblog/blog/templates/blog/article_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>article_page</title>
</head>
<body>
<h1>{{ article.title }}</h1>
<br/>
<h3>{{ article.content }}</h3>
<br/><br/>
<a href="{% url 'blog:edit_page' article.id %}">修改文章</a>
</body>
</html>

项目_Django/myblog/blog/templates/blog/edit_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Edit Page</title>
</head>
<body>
<form action="{% url 'blog:edit_action' %}" method="post">
    {% csrf_token %}

    {% if article %}
        <input type="hidden" name="article_id" value="{{ article.id }}"/>
        <label>文章标题
            <input type="text" name="title" value="{{ article.title }}"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content" value="{{ article.content }}"/>
        </label>
        <br/>

    {% else %}
        <input type="hidden" name="article_id" value="0"/>
        <label>文章标题
            <input type="text" name="title"/>
        </label>
        <br/>
        <label>文章内容
            <input type="text" name="content"/>
        </label>
        <br/>
    {% endif %}

    <input type="submit"/>
</form>
</body>
</html>

项目_Django/myblog/blog/templates/blog/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>
    <a href="{% url 'blog:edit_page' 0 %}">Hello,Blog!</a>
</h1>
<!--<h2>{{blog}}</h2>-->
<!--<h2>{{article.title}}</h2>-->
<!--<h3>{{article.content}}</h3>-->
{% for article in articles %}
    <a href="{% url 'blog:article_page' article.id %}">{{ article.title }}</a>
    <br/>
{% endfor %}
</body>
</html>

项目_Django/myblog/blog2/templates/blog2/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Hello,Blog2!</h1>
<h2>{{blog}}</h2>
</body>
</html>